name: sum3_uikit
description: "uikit"
version: 0.0.1

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_svg: ^2.2.3
  flutter_switch: ^0.3.2
  dropdown_button2: ^2.3.9
  google_fonts: ^8.0.0
  modal_bottom_sheet: ^3.0.0
  mask_text_input_formatter: ^2.0.0

flutter:

  # assets:
  #   - images/a_dot_burr.jpeg


#   fonts:
#     - family: CustomIcon
#       fonts:
#         - asset: fonts/CustomIcon.ttf

